"""
Django settings for accountsync project.

Generated by 'django-admin startproject' using Django 6.0.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
from pathlib import Path

from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-h@+t!tm#sq$g9)f(1j7w-zwayg46f5s@%_hx7=wy7_fvjvy46t'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['localhost', '127.0.0.1', 'testserver']

# Application definition

INSTALLED_APPS = [
    'unfold',  # Unfold admin theme - must be before django.contrib.admin
    'unfold.contrib.filters',  # Advanced filters
    'unfold.contrib.forms',  # Special form elements
    'django.contrib.admin',  # Django admin
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'django_filters',
    'drf_spectacular',
    'safedelete',
    'syncservice',
    # Celery相关应用
    'django_celery_beat',
    'django_celery_results',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'accountsync.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'accountsync.wsgi.application'

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.PageNumberPagination",
    "PAGE_SIZE": 10,
}

SPECTACULAR_SETTINGS = {
    'TITLE': 'AccountSync',
    'DESCRIPTION': '账号自动化',
    'VERSION': '1.0.0',
    'SERVE_INCLUDE_SCHEMA': False,  # 如果只想在 /api/schema/ 看到 JSON，不想在 UI 侧边栏看到一堆 JSON，可以设为 False
}

# 自定义定时任务配置
HR_SYNC_INTERVAL_MINUTES = 10  # 每10分钟同步一次
ACCOUNT_CREATION_INTERVAL_MINUTES = 5  # 每5分钟处理账号创建任务
TASK_CREATION_CHECK_INTERVAL_MINUTES = 10  # 每10分钟检查是否需要创建新任务

# 日志配置
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'file': {
            'level': 'INFO',
            'class': 'logging.FileHandler',
            'filename': 'logs/hr_sync.log',
            'formatter': 'verbose',
        },
        'console': {
            'level': 'INFO',
            'class': 'logging.StreamHandler',
            'formatter': 'simple',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'INFO',
    },
    'loggers': {
        'syncservice.cron.scheduler': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'syncservice.services': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
        'syncservice.management.commands.process_account_creation_tasks': {
            'handlers': ['file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}

DEFAULT_AUTO_FIELD = 'django.db.models.AutoField'

# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

load_dotenv()
# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.postgresql',
#         'NAME': os.getenv('DB_NAME'),
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST'),
#         'PORT': os.getenv('DB_PORT'),
#     }
# }
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',  # 引擎修改为 sqlite3
        'NAME': BASE_DIR / 'db.sqlite3',  # 这里指定数据库文件的路径
    }
}

# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'zh-hans'  # 简体中文

TIME_ZONE = 'Asia/Shanghai'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = 'static/'

# Unfold Admin Theme Configuration
UNFOLD = {
    "SITE_TITLE": "AccountSync 管理系统",
    "SITE_HEADER": "AccountSync",
    "SITE_SUBHEADER": "账号自动化管理系统",
    "SITE_URL": "/",
    "SITE_ICON": None,  # 移除图标
    "SITE_SYMBOL": None,  # 移除符号
    "SHOW_HISTORY": True,
    "SHOW_VIEW_ON_SITE": True,
    "SHOW_BACK_BUTTON": True,
    "ENVIRONMENT": "AccountSync.environment_callback",
    "THEME": "auto",  # Auto-detect light/dark mode
    "LOGIN": {
        "image": None,  # Can be customized later
    },
    "BORDER_RADIUS": "6px",
    "COLORS": {
        "primary": {
            "50": "oklch(97.7% .014 308.299)",
            "100": "oklch(94.6% .033 307.174)",
            "200": "oklch(90.2% .063 306.703)",
            "300": "oklch(82.7% .119 306.383)",
            "400": "oklch(71.4% .203 305.504)",
            "500": "oklch(62.7% .265 303.9)",
            "600": "oklch(55.8% .288 302.321)",
            "700": "oklch(49.6% .265 301.924)",
            "800": "oklch(43.8% .218 303.724)",
            "900": "oklch(38.1% .176 304.987)",
            "950": "oklch(29.1% .149 302.717)",
        },
    },
    "SIDEBAR": {
        "show_search": True,
        "show_all_applications": True,
        "navigation": [
            {
                "title": "人员管理",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "人员信息",
                        "icon": "people",
                        "link": "/admin/syncservice/hrperson/",
                    },
                    {
                        "title": "人员账号",
                        "icon": "account_circle",
                        "link": "/admin/syncservice/hrpersonaccount/",
                    },
                    {
                        "title": "创建任务",
                        "icon": "task",
                        "link": "/admin/syncservice/accountcreationtask/",
                    }
                ],
            },
            {
                "title": "系统配置",
                "separator": True,
                "collapsible": False,
                "items": [
                    {
                        "title": "部门映射",
                        "icon": "business",
                        "link": "/admin/syncservice/departmentmapping/",
                    },
                    {
                        "title": "人员类型",
                        "icon": "people",
                        "link": "/admin/syncservice/persontypemapping/",
                    },
                    {
                        "title": "系统配置",
                        "icon": "settings",
                        "link": "/admin/syncservice/syncconfig/",
                    },
                ],
            },
        ],
    },
}


def environment_callback(request):
    """
    环境标识回调函数
    """
    return ["开发环境", "warning"]  # warning 表示开发/测试环境


# Celery配置
# 使用Django数据库作为消息代理（开发环境推荐）
CELERY_BROKER_URL = 'django://'
CELERY_RESULT_BACKEND = 'django-db'  # 使用Django数据库存储任务结果

# Celery任务序列化
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_ACCEPT_CONTENT = ['json']

# 时区设置
CELERY_TIMEZONE = TIME_ZONE

# 任务路由
CELERY_TASK_ROUTES = {
    'syncservice.tasks.sync_hr_persons_task': {'queue': 'hr_sync'},
    'syncservice.tasks.create_account_tasks_task': {'queue': 'account_tasks'},
    'syncservice.tasks.process_account_creation_tasks_task': {'queue': 'account_processing'},
}

# Beat调度器配置
from celery.schedules import crontab

CELERY_BEAT_SCHEDULE = {
    'sync-hr-persons': {
        'task': 'syncservice.tasks.sync_hr_persons_task',
        'schedule': crontab(minute='*/10'),  # 每10分钟执行一次
    },
    'create-account-tasks': {
        'task': 'syncservice.tasks.create_account_tasks_task',
        'schedule': crontab(minute='*/10'),  # 每10分钟执行一次
    },
    'process-account-creation-tasks': {
        'task': 'syncservice.tasks.process_account_creation_tasks_task',
        'schedule': crontab(minute='*/5'),  # 每5分钟执行一次
    },
}
